name: Publish NuGet Packages

on:
  workflow_dispatch:
    inputs:
      build_run_id:
        description: 'Run ID do build que gerou os pacotes (.nupkg)'
        required: true

permissions:
  actions: read
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v5.0.0
        with:
          run-id: ${{ inputs.build_run_id }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish to NuGet.org
        run: dotnet nuget push "*.nupkg" \
              --api-key ${{ secrets.NUGET_API_KEY }} \
              --source https://api.nuget.org/v3/index.json \
              --skip-duplicate
